# INTRO

short term rentals are primary residences' extra living accomodation rented out for less than 28 consecutive days

this dataset contains currently active Short-term rentals

the dataset is static, doesn't have time series feature. GEO postal code are generalized

redundant: 
- unit (just the unit number)
- ward_number/ward_name: just a grouping of postal codes

fields:
- postcode
- property_type

In [1]:
import polars as pl

In [ ]:
df = pl.read_csv("../data/short-term-rentals-registration.csv")

In [3]:
df.schema

Schema([('_id', Int64),
        ('operator_registration_number', String),
        ('address', String),
        ('unit', String),
        ('postal_code', String),
        ('property_type', String),
        ('ward_number', Int64),
        ('ward_name', String)])

In [4]:
q = (
    df.lazy()
    .group_by("postal_code")
    .agg(
        pl.len().alias("postcode_count")
    )
    .sort(by="postcode_count", descending=True)
)

rentals_by_postcode = q.collect()

In [10]:
q = (
    df.lazy()
    .group_by("property_type")
    .agg(
        pl.len().alias("property_type_count")
    )
    .sort(by="property_type_count", descending=True)
)

rentals_by_units = q.collect()

In [8]:
rentals_by_postcode

shape: (10, 2)
┌─────────────┬───────┐
│ postal_code ┆ count │
│ ---         ┆ ---   │
│ str         ┆ u32   │
╞═════════════╪═══════╡
│ M5V         ┆ 1550  │
│ M5J         ┆ 475   │
│ M6J         ┆ 318   │
│ M6K         ┆ 291   │
│ M6H         ┆ 248   │
│ M5A         ┆ 248   │
│ M5R         ┆ 241   │
│ M5B         ┆ 208   │
│ M6G         ┆ 206   │
│ M4L         ┆ 191   │
└─────────────┴───────┘

In [11]:
rentals_by_units

shape: (7, 2)
┌────────────────────────────┬─────────────────────┐
│ property_type              ┆ property_type_count │
│ ---                        ┆ ---                 │
│ str                        ┆ u32                 │
╞════════════════════════════╪═════════════════════╡
│ Single/Semi-detached House ┆ 3726                │
│ Condominium                ┆ 3304                │
│ Apartment                  ┆ 678                 │
│ Townhouse/ Row House       ┆ 621                 │
│ Duplex/Triplex/Fourplex    ┆ 377                 │
│ Single-family detached     ┆ 1                   │
│ Semi-detached House        ┆ 1                   │
└────────────────────────────┴─────────────────────┘