# TPL

- Library programs and events feed
- Library visits
-

In [1]:
import os
os.chdir("../")
cwd = os.getcwd()
print(cwd)

/home/ruchirich/Documents/repositories/toronto-open-data/tpl

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd

from utils.download_data import download_data
import math

In [13]:
pd.set_option('display.max_colwidth', 50)

In [15]:
pd.set_option('display.max_columns', None)

In [3]:
# Datasets are called "packages". Each package can contain many "resources"
# To retrieve the metadata for this package and its resources, use the package name in this page's URL:
params = { "id": "library-branch-programs-and-events-feed"}
download_file = cwd+"/data/library-branch-programs-and-events-feed.csv"

download_data(params, download_file)

In [19]:
# df = pd.read_csv(download_file, index_col='Timestamp', parse_dates=True, date_format="ISO8601", usecols=['Timestamp', 'Sales Count', 'Redemption Count'])
df = pd.read_csv(download_file)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4435 entries, 0 to 4434
Data columns (total 26 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   _id              4435 non-null   int64
 1   title            4435 non-null   object
 2   startdate        4435 non-null   object
 3   enddate          16 non-null     object
 4   starttime        4419 non-null   object
 5   endtime          4419 non-null   object
 6   library          4435 non-null   object
 7   location         2180 non-null   object
 8   description      4435 non-null   object
 9   pagelink         4435 non-null   object
 10  id               4435 non-null   int64
 11  rcid             4435 non-null   int64
 12  eventtype1       4435 non-null   object
 13  eventtype2       1481 non-null   object
 14  eventtype3       200 non-null    object
 15  agegroup1        4435 non-null   object
 16  agegroup2        1339 non-null   object
 17  agegroup3        208 non-null    object
 18  supportlink      294 non-null    object
 19  supportlinktext  289 non-null    object
 20  imagepath        78 non-null     object
 21  imagetext        1 non-null      object
 22  imageheight      108 non-null    float64
 23  imagewidth       108 non-null    float64
 24  otherinfo        1123 non-null   object
 25  lastupdated      4435 non-null   object
dtypes: float64(2), int64(3), object(21)
memory usage: 901.0+ KB

In [16]:
df.head()

,_id,title,startdate,enddate,starttime,endtime,library,location,description,pagelink,id,rcid,eventtype1,eventtype2,eventtype3,agegroup1,agegroup2,agegroup3,supportlink,supportlinktext,imagepath,imagetext,imageheight,imagewidth,otherinfo,lastupdated
0,1,Basic Tech Help: Senior's E-Connect,2024-12-13,2025-12-31,NaN,NaN,Cedarbrae,NaN,"Do you have a phone, tablet or computer you do...",https://www.torontopubliclibrary.ca/detail.jsp...,530952,0,00-Computer & Library Training,NaN,NaN,Older Adult,Adult,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-01-10T15:19:17Z
1,2,English Book Club,2025-01-18,2025-12-20,NaN,NaN,Cedarbrae,NaN,Join our monthly Book Club to discuss literatu...,https://www.torontopubliclibrary.ca/detail.jsp...,530953,0,00-Book Clubs & Writers Groups,NaN,NaN,Adult,Older Adult,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-12-09T15:49:56Z
2,3,Creative Writing Group,2025-01-29,2025-12-17,NaN,NaN,Cedarbrae,NaN,Looking to improve your English Writing skills...,https://www.torontopubliclibrary.ca/detail.jsp...,530958,0,00-Book Clubs & Writers Groups,NaN,NaN,Adult,Older Adult,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-12-09T15:54:38Z
3,4,Tea & Entertainment,2025-01-10,2025-04-25,NaN,NaN,North York Central Library,NaN,Enjoy watching DVDs in the Library Auditorium ...,https://www.torontopubliclibrary.ca/detail.jsp...,532007,0,00-Culture Arts & Entertainment,NaN,NaN,Older Adult,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-12-12T18:22:58Z
4,5,Patterns and Puffed Sleeves: Costume Design Th...,2024-10-05,2025-01-26,NaN,NaN,Toronto Reference Library,NaN,In celebration of the 150th birthday of Lucy M...,https://www.torontopubliclibrary.ca/detail.jsp...,519981,0,00-Art Exhibits,01-Anne of Green Gables,00-Culture Arts & Entertainment,All Ages,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{""smallImageURL"":""https://tpl.razuna.com/asset...",2024-12-05T14:56:28Z

In [17]:
df.location.unique()

array([nan, 'Auditorium (FCCR)', 'Program Room',
       'Program Room - 2nd Floor', 'Story Room', 'Multipurpose Room',
       'Learning Centre', 'Meeting Room', 'Meeting Room 1',
       'Adult Program Room', "Children's Program Room", 'theatre',
       'Auditorium', 'Youth Hub', 'Community Room',
       'Digital Innovation Hub', 'Small Meeting Room - 2ndÂ\xa0Floor',
       'Learning Centre 1', 'Enhanced Learning Centre', 'Room 200',
       'Elearning Lab', 'Discussion Room', "Founders' Room", 'Room 101',
       'TD Gallery', 'Program Room - Basement', 'Small Program Room',
       'Fabrication Studio', 'Basement', 'Program Room - Main Floor',
       'Room 224', 'Art Gallery',
       'Digital Innovation Hub - 2ndÂ\xa0Floor', 'Beeton Hall',
       'Browsery', 'Urban Living Room', 'Bram & Bluma Appel Salon',
       'Hinton Learning Theatre', 'Room 2/3', 'Room 1', 'meeting room',
       'Jack Rabinovitch Reading Room', 'Concourse Event Space'],
      dtype=object)

In [29]:
for k, v in df.groupby(['eventtype1', 'eventtype2', 'eventtype3']).groups.items():
    print(k)
    print(v)
    break

('00-After School', '00-Culture Arts & Entertainment', '00-Hobbies Crafts & Games')
Index([1216, 1659, 2065, 2460], dtype='int64')

In [30]:
event_groups = df.groupby(['eventtype1', 'eventtype2', 'eventtype3'])

In [32]:
group_1 = event_groups.get_group(('00-After School', '00-Culture Arts & Entertainment', '00-Hobbies Crafts & Games'))

In [34]:
group_1.head()

,_id,title,startdate,enddate,starttime,endtime,library,location,description,pagelink,id,rcid,eventtype1,eventtype2,eventtype3,agegroup1,agegroup2,agegroup3,supportlink,supportlinktext,imagepath,imagetext,imageheight,imagewidth,otherinfo,lastupdated
1216,1217,WAITLIST - Brush & Beyond Visual Arts Series,2025-02-04,NaN,5:00 PM,6:30 PM,Hillcrest,Program Room,Brush & Beyond has partnered with Hillcrest Li...,https://www.torontopubliclibrary.ca/detail.jsp...,533941,33438,00-After School,00-Culture Arts & Entertainment,00-Hobbies Crafts & Games,School-Age Children,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{""smallImageURL"":""https://tpl.razuna.com/asset...",2025-01-10T15:46:35Z
1659,1660,WAITLIST - Brush & Beyond Visual Arts Series,2025-02-11,NaN,5:00 PM,6:30 PM,Hillcrest,Program Room,Brush & Beyond has partnered with Hillcrest Li...,https://www.torontopubliclibrary.ca/detail.jsp...,533942,33438,00-After School,00-Culture Arts & Entertainment,00-Hobbies Crafts & Games,School-Age Children,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{""smallImageURL"":""https://tpl.razuna.com/asset...",2025-01-10T15:46:35Z
2065,2066,WAITLIST - Brush & Beyond Visual Arts Series,2025-02-18,NaN,5:00 PM,6:30 PM,Hillcrest,Program Room,Brush & Beyond has partnered with Hillcrest Li...,https://www.torontopubliclibrary.ca/detail.jsp...,533943,33438,00-After School,00-Culture Arts & Entertainment,00-Hobbies Crafts & Games,School-Age Children,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{""smallImageURL"":""https://tpl.razuna.com/asset...",2025-01-10T15:46:35Z
2460,2461,WAITLIST - Brush & Beyond Visual Arts Series,2025-02-25,NaN,5:00 PM,6:30 PM,Hillcrest,Program Room,Brush & Beyond has partnered with Hillcrest Li...,https://www.torontopubliclibrary.ca/detail.jsp...,533944,33438,00-After School,00-Culture Arts & Entertainment,00-Hobbies Crafts & Games,School-Age Children,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{""smallImageURL"":""https://tpl.razuna.com/asset...",2025-01-10T15:46:35Z